site_name: AI HEART Project

# Theme configuration
theme:
  name: material
  palette:
    primary: amber
  logo: img/title.svg
  favicon: img/icon.png
  custom_dir: overrides
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky

# Navigation
nav:
  - Home: index.md
  - About: about.md
  - Reports:
    - Safety Silencing Report:
      - Safety Silencing in Public LLMs: reports/ai-safety-silencing/README.md
      - Mitigation:
        - Mitigation Strategies: reports/ai-safety-silencing/mitigations/README.md
        - Drift Monitor: reports/ai-safety-silencing/mitigations/drift-monitor.md
      - Supporting Documents:
        - Human Impact: reports/ai-safety-silencing/supporting-documents/human-impact.md
        - Safety Collapse: reports/ai-safety-silencing/supporting-documents/safety-collapse.md
        - Further Reading: reports/ai-safety-silencing/supporting-documents/further-reading.md
  - Articles:
    - articles/methodological-agnosticism.md
    - articles/empathy-for-ai.md
    - articles/ai-addiction.md

# Footer
copyright: Copyright &copy; 2025 AI HEART Project
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AI_HEARTproject
    - icon: fontawesome/brands/github
      link: https://github.com/Yasmin-FY
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qCddXfnkz

plugins:
  - meta-descriptions
  - meta

markdown_extensions:
  - footnotes

extra_css:
  - stylesheets/extra.css?v=20251217