site_name: AI HEART Project

# Theme configuration
theme:
  name: material
  palette:
    primary: amber
  logo: img/icon.jpeg
  language: en

# Navigation
nav:
  - Home: index.md
  - Reports:
    - Safety Silencing in Public LLMs:
      - Safety Silencing Report: reports/ai-safety-silencing/README.md
      - Mitigation Strategies: reports/ai-safety-silencing/mitigations/README.md
      - Human Impact: reports/ai-safety-silencing/supporting-documents/human-impact.md
  - Articles:
    - AI Addiction: reports/ai-safety-silencing/articles/ai-addiction.md

# Footer
copyright: Copyright &copy; 2025 AI HEART Project
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AI_HEARTproject
    - icon: fontawesome/brands/github
      link: https://github.com/Yasmin-FY

plugins:
  - meta-descriptions